// Generated by CoffeeScript 1.3.3
(function() {

  window.RubyGems = function(name) {
    return {
      query: name,
      configs: {
        search: "https://rubygems.org/search?query=",
        api: "https://rubygems.org/api/v1/gems/"
      },
      exists: false,
      info: {},
      fetch: function() {
        var that;
        that = this;
        return $.ajax({
          url: this.configs.api + this.query + ".json",
          error: function() {
            return that.exists = false;
          },
          success: function(data) {
            that.exists = true;
            return that.info = data;
          }
        });
      }
    };
  };

}).call(this);
