// Generated by CoffeeScript 1.3.3
(function() {
  var openTab;

  if (localStorage["open_in"] === void 0) {
    localStorage["open_in"] = "1";
  }

  window.RubyGems = function(name) {
    return {
      query: name,
      configs: {
        search: "https://rubygems.org/search?query=",
        api: "https://rubygems.org/api/v1/gems/"
      },
      exists: false,
      info: {},
      fetch: function() {
        var that;
        that = this;
        return $.ajax({
          url: this.configs.api + this.query + ".json",
          beforeSend: function() {
            return $('#search').addClass('loading');
          },
          error: function() {
            return that.exists = false;
          },
          success: function(data) {
            that.exists = true;
            return that.info = data;
          }
        });
      }
    };
  };

  openTab = function(url) {
    if (localStorage["open_in"] === "1") {
      return chrome.tabs.getSelected(null, function(tab) {
        if (/rubygems\.org|chrome:\/\/newtab/.test(tab.url)) {
          chrome.tabs.update(tab.id, {
            url: url
          });
          return window.close();
        } else {
          return chrome.tabs.create({
            url: url
          });
        }
      });
    } else {
      return chrome.tabs.create({
        url: url
      });
    }
  };

  window.apply = function(query, omnibox) {
    var gem;
    if (omnibox == null) {
      omnibox = true;
    }
    gem = new window.RubyGems(query);
    gem.fetch();
    return $(document).ajaxComplete(function() {
      var url;
      if (gem.exists) {
        url = gem.info.project_uri;
      } else {
        url = gem.configs.search + gem.query + "&source=chrome-extension";
      }
      if (omnibox) {
        return chrome.tabs.getSelected(void 0, function(tab) {
          return chrome.tabs.update(tab.id, {
            url: url
          });
        });
      } else {
        return openTab(url);
      }
    });
  };

}).call(this);
