// Generated by CoffeeScript 1.3.3
(function() {
  var saveOptions;

  saveOptions = function() {
    if ($(".sametab").is(":checked")) {
      localStorage["open_in"] = "1";
    } else {
      localStorage["open_in"] = "0";
    }
    $(".message").html("Options Saved.");
    return setTimeout((function() {
      return $(".message").html("");
    }), 1000);
  };

  $(document).ready(function() {
    if (localStorage["open_in"] === "1") {
      $('.sametab').attr("checked", true);
    } else {
      $('.newtab').attr("checked", true);
    }
    return $("form").submit(function() {
      saveOptions();
      return false;
    });
  });

}).call(this);
