// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    return $("form").submit(function() {
      apply($('#search').val(), false);
      return false;
    });
  });

}).call(this);
